spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDBMS_URL}
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
      open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration, classpath:db/seed/dev
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE}

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true
