version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - ${REDIS_OUT_PORT}:${REDIS_IN_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]

volumes:
  redis_data:
    driver: local
