INSERT INTO techEducation_review (member_id, tech_education_type_id, rating, content, item_id, created_at, modified_at)
VALUES (1, 1, 5, "TechTube-1 리뷰 내용", 1, NOW(), NOW()),
       (2, 1, 5, "TechTube-2 리뷰 내용", 2, NOW(), NOW()),
       (1, 1, 5, "TechTube-3 리뷰 내용", 3, NOW(), NOW()),
       (2, 1, 5, "TechTube-4 리뷰 내용", 4, NOW(), NOW()),
       (1, 1, 5, "TechTube-5 리뷰 내용", 5, NOW(), NOW()),
       (2, 1, 5, "TechTube-6 리뷰 내용", 6, NOW(), NOW()),
       (1, 1, 5, "TechTube-7 리뷰 내용", 7, NOW(), NOW()),
       (2, 1, 5, "TechTube-8 리뷰 내용", 8, NOW(), NOW()),
       (1, 1, 5, "TechTube-9 리뷰 내용", 9, NOW(), NOW()),
       (2, 1, 5, "TechTube-10 리뷰 내용", 10, NOW(), NOW()),
       (1, 2, 5, "TechBook-1 리뷰 내용", 1, NOW(), NOW()),
       (2, 2, 5, "TechBook-2 리뷰 내용", 2, NOW(), NOW()),
       (1, 2, 5, "TechBook-3 리뷰 내용", 3, NOW(), NOW()),
       (2, 2, 5, "TechBook-4 리뷰 내용", 4, NOW(), NOW()),
       (1, 2, 5, "TechBook-5 리뷰 내용", 5, NOW(), NOW()),
       (2, 2, 5, "TechBook-6 리뷰 내용", 6, NOW(), NOW()),
       (1, 2, 5, "TechBook-7 리뷰 내용", 7, NOW(), NOW()),
       (2, 2, 5, "TechBook-8 리뷰 내용", 8, NOW(), NOW()),
       (1, 2, 5, "TechBook-9 리뷰 내용", 9, NOW(), NOW()),
       (2, 2, 5, "TechBook-10 리뷰 내용", 10, NOW(), NOW());