spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDBMS_URL}
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
      open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration, classpath:db/seed/prod