spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            redirect-uri: "${BACKEND_URL}/login/oauth2/code/kakao"
            authorization_grant_type: authorization_code
            client-authentication-method: client_secret_post
            client_name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
custom:
  jwt:
    accessToken:
      secret: ${JWT_ACCESS_TOKEN_SECRET}
      expirationSeconds: "#{20 * 60}" # 20 minutes
    refreshToken:
      secret: ${JWT_REFRESH_TOKEN_SECRET}
      expirationSeconds: "#{30 * 24 * 60 * 60}" # 30 days
