SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS oauth_provider;
ALTER TABLE oauth DROP FOREIGN KEY oauth_ibfk_2;
ALTER TABLE oauth DROP COLUMN auth_provider_id;
ALTER TABLE oauth ADD COLUMN provider_name VARCHAR(255) NOT NULL;
SET FOREIGN_KEY_CHECKS = 1;
